apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: fluent-bit.enabled
  name: fluent-bit
  repository: https://fluent.github.io/helm-charts
  version: 0.19.5
description: A Helm chart for SSP Analytics
name: ssp-analytics
type: application
version: 0.1.2
