
apiVersion: v1
data:
  fluent-bit-filter.conf: |
    [FILTER]
        Name                kubernetes
        Match               ssp_msg.*
        Kube_Tag_Prefix     ssp_msg.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Keep_Log            Off
        #Merge_Log_Key       ""
        K8S-Logging.Parser  Off
        #K8S-Logging.Exclude On
        #Use_Journal         On
  fluent-bit-input.conf: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/{{ required "***** A valid sspReleaseName value required in values.yaml or passed in via --set sspReleaseName=<value>!  If this is an upgrade, specify --reuse-values. *****" .Values.sspReleaseName }}-ssp-*.log
        Parser           cri
        Tag              ssp_msg.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  Off
        Ignore_Older     60s
        DB               /var/log/tail-containers-state-ssp-ssp.db
        DB.Sync          Normal
  fluent-bit-output.conf: |
    [OUTPUT]
        Name                http
        Match               ssp_audit
        Host    {{ .Values.ssp.analytics.host }}
        Port    {{ .Values.ssp.analytics.port }}
        URI     /sspLogStream
        Format     json
    [OUTPUT]
        Name                http
        Match               ssp_log
        Host    {{ .Values.ssp.analytics.host }}
        Port    {{ .Values.ssp.analytics.port }}
        URI     /sspLogStream
        Format     json
  fluent-bit-service.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        Streams_File fluent-bit-streamer.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        Health_Check On
  fluent-bit-streamer.conf: |
    [STREAM_TASK]
        Name   ssp_log
        Exec   CREATE STREAM ssp_log WITH (tag='ssp_log') AS SELECT * from TAG:'ssp_msg.*' WHERE type = 'log';
    [STREAM_TASK]
        Name   ssp_audit
        Exec   CREATE STREAM ssp_audit WITH (tag='ssp_audit') AS SELECT * from TAG:'ssp_msg.*' WHERE type = 'audit';
    [STREAM_TASK]
        Name   ssp_tp_log
        Exec   CREATE STREAM ssp_tp_log WITH (tag='ssp_tp_log') AS SELECT * from TAG:'ssp_msg.*' WHERE NOT @record.contains(type);
  fluent-bit.conf: |
    @INCLUDE fluent-bit-service.conf
    @INCLUDE fluent-bit-input.conf
    @INCLUDE fluent-bit-filter.conf
    @INCLUDE fluent-bit-output.conf
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Keep   off
        Time_Key    time
        # TBD: update to use log entry's timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Decode_Field_As escaped log
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: infra-ssp
    meta.helm.sh/release-namespace: analytics
  creationTimestamp: "2022-03-06T21:36:19Z"
  labels:
    app: ssp-infra
    app.kubernetes.io/managed-by: Helm
    chart: ssp-infra-1.0.2648
    heritage: Helm
    release: infra-ssp
  name: ssp-fluent-bit-config
  namespace: analytics
