apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ssp.analytics.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.ssp.analytics.name }}
  replicas: 1 
  revisionHistoryLimit: 0
  progressDeadlineSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.ssp.analytics.name }}
    spec:
      containers:
      - name: {{ .Values.ssp.analytics.name }}
        image: pconnor/ssp-metrics-exporter:latest
        ports:
        - hostPort: 8080
          name: web
          containerPort: 8080
